# Variáveis (Token pego do auth.http)
@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlLXJlZ2lzdHJvQGV4ZW1wbG8uY29tIiwic3ViIjoiNjkwYTliMzRkMzgxZmM2ZTA2NWUyYzJmIiwiaWF0IjoxNzYyMzQyNjQ0LCJleHAiOjE3NjI5NDc0NDR9.HMv9sQuUcq-y2HxkjuHiYzVFCjahuFyF09BPn2Mp6ro

# ID de uma unidade (atualize após criar)
@unitId = 690b3d4347ac1835355e1849

# ---------------------------------
# UNIDADES DE SAÚDE (CRUD)
# ---------------------------------

### 1. (PROTEGIDO) Criar uma nova unidade
POST {{host}}/health-units
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "UBS Centro",
  "address": "Rua Principal, 123, Centro"
}

### 2. (PÚBLICO) Buscar todas as unidades
GET {{host}}/health-units

### 3. (PÚBLICO) Buscar uma unidade por ID
GET {{host}}/health-units/{{unitId}}

### 4. (PROTEGIDO) Atualizar uma unidade
PATCH {{host}}/health-units/{{unitId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "address": "Rua Principal, 123, Centro, Cidade Nova"
}

### 5. (PROTEGIDO) Deletar uma unidade
DELETE {{host}}/health-units/{{unitId}}
Authorization: Bearer {{token}}