# Variáveis (Token pego do auth.http)
@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlLXJlZ2lzdHJvQGV4ZW1wbG8uY29tIiwic3ViIjoiNjkwYTliMzRkMzgxZmM2ZTA2NWUyYzJmIiwiaWF0IjoxNzYyOTUxMDYxLCJleHAiOjE3NjM1NTU4NjF9.7r9KRwVyjPJV79fteUjLgejuKAdMTSWvi3Y-wicH9sQ

# ID de um médico (atualize após criar)
@doctorId = 690b3b34f795f83d754f398f

# ID de uma Unidade (pegue do health-unit.http)
@healthUnitId = 690b3d4347ac1835355e1849

# ---------------------------------
# MÉDICOS (CRUD)
# ---------------------------------

### 1. (PROTEGIDO) Criar um novo médico
# Requer token de admin/login
POST {{host}}/doctors
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dr. Julia Santana",
  "crm": "098765443-RJ",
  "specialty": "Fisioterapia",
  "healthUnitId": "{{healthUnitId}}",
  "availability": [
    {
      "date": "2025-11-29",
      "times": ["08:00", "11:00", "12:00"]
    },
    {
      "date": "2025-12-26",
      "times": ["18:00", "19:00"]
    }
  ]
}

### 2. (PÚBLICO) Buscar todos os médicos
GET {{host}}/doctors

### 3. (PÚBLICO) Buscar médicos por especialidade
GET {{host}}/doctors?specialty=Cardiologia

### 4. (PÚBLICO) Buscar um médico por ID
GET {{host}}/doctors/{{doctorId}}

### 5. (PROTEGIDO) Atualizar um médico
PATCH {{host}}/doctors/{{doctorId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dra. Ana Costa Silva"
}

### 6. (PROTEGIDO) Deletar um médico
DELETE {{host}}/doctors/6913223b1a8a39c1a2d68a92
Authorization: Bearer {{token}}