# Variáveis (Token pego do auth.http)
@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlLXJlZ2lzdHJvQGV4ZW1wbG8uY29tIiwic3ViIjoiNjkwYTliMzRkMzgxZmM2ZTA2NWUyYzJmIiwiaWF0IjoxNzYyOTUxMDYxLCJleHAiOjE3NjM1NTU4NjF9.7r9KRwVyjPJV79fteUjLgejuKAdMTSWvi3Y-wicH9sQ

# ID de um médico (atualize após criar)
@doctorId = 690b3b34f795f83d754f398f

# ID de uma Unidade (pegue do health-unit.http)
@healthUnitId = 691bb3959f2193696bd1d2c7

# ---------------------------------
# MÉDICOS (CRUD)
# ---------------------------------

### 1. (PROTEGIDO) Criar um novo médico
# Requer token de admin/login
POST {{host}}/doctors
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dr. Vitor Santana",
  "crm": "99099-RJ",
  "specialty": "Cardiologia",
  "healthUnitId": "{{healthUnitId}}",
  "availability": [
    {
      "date": "2025-11-29",
      "times": ["06:00", "07:00", "13:00"]
    },
    {
      "date": "2025-12-26",
      "times": ["18:30", "17:45"]
    }
  ]
}

### 2. (PÚBLICO) Buscar todos os médicos
GET {{host}}/doctors

### 3. (PÚBLICO) Buscar médicos por especialidade
GET {{host}}/doctors?specialty=Cardiologia

### 4. (PÚBLICO) Buscar um médico por ID
GET {{host}}/doctors/{{doctorId}}

### 5. (PROTEGIDO) Atualizar um médico
PATCH {{host}}/doctors/{{doctorId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dra. Ana Costa Silva"
}

### 6. (PROTEGIDO) Deletar um médico
DELETE {{host}}/doctors/6915ccb0bf779d5c30aee627
Authorization: Bearer {{token}}